
package hi.clientAxis2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "hi", targetNamespace = "http://hello", wsdlLocation = "http://localhost:8080/axis2/services/hi?wsdl")
public class Hi
    extends Service
{

    private final static URL HI_WSDL_LOCATION;
    private final static WebServiceException HI_EXCEPTION;
    private final static QName HI_QNAME = new QName("http://hello", "hi");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/axis2/services/hi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HI_WSDL_LOCATION = url;
        HI_EXCEPTION = e;
    }

    public Hi() {
        super(__getWsdlLocation(), HI_QNAME);
    }

    public Hi(WebServiceFeature... features) {
        super(__getWsdlLocation(), HI_QNAME, features);
    }

    public Hi(URL wsdlLocation) {
        super(wsdlLocation, HI_QNAME);
    }

    public Hi(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HI_QNAME, features);
    }

    public Hi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hi(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HiPortType
     */
    @WebEndpoint(name = "hiHttpSoap11Endpoint")
    public HiPortType getHiHttpSoap11Endpoint() {
        return super.getPort(new QName("http://hello", "hiHttpSoap11Endpoint"), HiPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HiPortType
     */
    @WebEndpoint(name = "hiHttpSoap11Endpoint")
    public HiPortType getHiHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello", "hiHttpSoap11Endpoint"), HiPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HI_EXCEPTION!= null) {
            throw HI_EXCEPTION;
        }
        return HI_WSDL_LOCATION;
    }

}
